# Generated by Django 5.1.1 on 2024-09-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_alter_customuser_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
