# Generated by Django 5.1.1 on 2024-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_alter_customuser_avatar_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=False, upload_to='images/posters/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, default=False, to='movies_app.movie'),
        ),
    ]
