# Generated by Django 5.1.1 on 2024-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_alter_customuser_avatar_alter_customuser_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarked',
            field=models.ManyToManyField(to='movies_app.movie'),
        ),
    ]
