# Generated by Django 5.1.1 on 2024-09-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_alter_customuser_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarked',
            field=models.ManyToManyField(related_name='movie', to='movies_app.movie'),
        ),
    ]
