# Generated by Django 5.1.1 on 2024-09-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_alter_customuser_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/users/default.png', upload_to='images/users/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, default=False, related_name='movie', to='movies_app.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='images/posters/default.jpeg', upload_to='images/posters/'),
        ),
    ]
