# Generated by Django 5.1.1 on 2024-09-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0008_alter_customuser_avatar_alter_customuser_bookmarked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='movies_app.actor'),
        ),
    ]
