# Generated by Django 5.1.1 on 2024-09-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0009_alter_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='movies_app.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='movies_app.genre'),
        ),
    ]
