# Generated by Django 5.1.1 on 2024-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0011_remove_movie_actors_remove_movie_genre_movie_actors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
