# Generated by Django 5.1.1 on 2024-09-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0014_director_remove_movie_director_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='lastname',
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
